name: CI

concurrency: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - run: |
            echo "RUST_VERSION=$(cat .rust-version)" >> $GITHUB_ENV

    - name: Setup Node
      uses: actions/setup-node@v6.3.0
      with:
        node-version-file: .node-version

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Build
      run: |
            pnpm install
            cargo tauri build --verbose

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: $RUST_VERSION

    - name: Run tests
      run: cargo test --verbose
